$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}
background {
    monitor = eDP-1
    path = ~/Downloads/wallpaper/cue.png
    blur_passes = 0
}

input-field {
    monitor = eDP-1
    # 位置：水平居中、垂直偏下
    # 尺寸
    size = 300, 60
    # 样式

    outline_thickness = 0
    dots_spacing = 0.5
    inner_color = rgba(200, 200, 200, 0.5)
    outer_color = rgba(50, 50, 50, 0.5)

    font_family = $font
    font_color = rgba(255, 255, 255, 1.0)
    placeholder_text = Password

    position = 0, 0
    halign = center
    valign = center

    shadow_passes = 2
}

# TIME
label {
    monitor = eDP-1
    text = $TIME
    font_size = 150

    position = 0, -200
    halign = center
    valign = top

    shadow_passes = 2
}

# DATE
label {
    monitor = eDP-1
    text = cmd[update:60000] date +"%Y-%m-%d, %A"
    font_size = 30
    font_family = $font

    position = 0, -450
    halign = center
    valign = top

    shadow_passes = 2
}

# 重启按钮
image {
    monitor = eDP-1
    path = ~/.config/hypr/icons/reboot.png
    size = 48
    rounding = 8
    border_color = rgba(200, 200, 200, 0.5)
    position = -150, 50
    halign = right
    valign = bottom
    zindex = 5
    onclick = reboot

    shadow_passes = 2
}

# 关机按钮
image {
    monitor = eDP-1
    path = ~/.config/hypr/icons/shutdown.png
    size = 48
    rounding = 8
    border_color = rgba(200, 200, 200, 0.5)
    position = -50, 50
    halign = right
    valign = bottom
    zindex = 5
    onclick = shutdown now

    shadow_passes = 2
}

